export const Images = {
  redirect: require('../app/assets/images/redirect.png'),
  Logo: require('../app/assets/images/logo.png'),
  success: require('../app/assets/images/success.png'),
  vip: require('../app/assets/images/vip.png'),
  recharge: require('../app/assets/images/recharge.png'),
  withdraw: require('../app/assets/images/withdraw.png'),
  send: require('../app/assets/images/icons/send.png'),
  receive: require('../app/assets/images/icons/received.png'),
  whatsapp: require('../app/assets/images/icons/whatsapp.png'),
  telegram: require('../app/assets/images/icons/telegram.png'),
  email: require('../app/assets/images/icons/email.png'),
  sms: require('../app/assets/images/icons/sms.png'),
  card: require('../app/assets/images/card.png'),
  costumer: require('../app/assets/images/icons/costumer.png'),
  ontime: require('../app/assets/images/icons/on-time.png'),
  quality: require('../app/assets/images/icons/quality.png'),
  review: require('../app/assets/images/icons/review.png'),
  qf: require('../app/assets/images/icons/qf.png'),
  secure: require('../app/assets/images/icons/payment.png'),
  flag: require('../app/assets/images/icons/logo.png'),
  ssl: require('../app/assets/images/icons/transaction.png'),
  banner: require('../app/assets/images/icons/banner.png'),
  UAE: require('../app/assets/images/icons/united.png'),
};
