export const Images = {
  redirect: require('../app/assets/images/redirect.png'),
  Logo: require('../app/assets/images/logo.png'),
  success: require('../app/assets/images/success.png'),
  vip: require('../app/assets/images/vip.png'),
  recharge: require('../app/assets/images/recharge.png'),
  withdraw: require('../app/assets/images/withdraw.png'),
  send: require('../app/assets/images/icons/send.png'),
  receive: require('../app/assets/images/icons/received.png'),
  qrcode: require('../app/assets/images/qrcode.png'),
  vip0: require('../app/assets/images/vip/vip0.png'),
  vip1: require('../app/assets/images/vip/vip1.png'),
  vip2: require('../app/assets/images/vip/vip2.png'),
  vip3: require('../app/assets/images/vip/vip3.png'),
  vip4: require('../app/assets/images/vip/vip4.png'),
  vip5: require('../app/assets/images/vip/vip5.png'),
  vip6: require('../app/assets/images/vip/vip6.png'),
  whatsapp: require('../app/assets/images/icons/whatsapp.png'),
  telegram: require('../app/assets/images/icons/telegram.png'),
  email: require('../app/assets/images/icons/email.png'),
  sms: require('../app/assets/images/icons/sms.png'),
};
