import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  ViewTop: {
    backgroundColor: '#1EA073',
    width: '100%',
    height: 260,
    position: 'relative',
    display: 'flex',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 50,
    zIndex: 1,
    borderBottomRightRadius: 26,
    borderBottomLeftRadius: 26,
  },
  ViewMeduim: {
    backgroundColor: '#E8F7F2',
    width: '90%',
    height: '100%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    zIndex: 20,
    position: 'relative',
  },
  circleView: {
    position: 'relative',
    width: 75,
    height: 75,
    backgroundColor: 'white',
    borderRadius: 50,
    top: -23,
    left: 10,
    borderWidth: 2,
    borderColor: '#1EA073',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallCircle: {
    width: 30,
    height: 30,
    backgroundColor: 'green',
    borderRadius: 50,
    bottom: 0,
    right: -6,
    position: 'absolute',
    borderWidth: 2,
    borderColor: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  validation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },

  approved: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '90%',
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    height:290,
    gap: 26,
    backgroundColor: 'white',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
});
